# Generated by Django 4.2 on 2024-04-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lochs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('loch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lochs.loch')),
            ],
        ),
    ]
